create extension if not exists pgcrypto;

do $$ begin create type receipt_status as enum ('processing', 'needs_review', 'confirmed', 'rejected', 'failed'); exception when duplicate_object then null; end $$;
do $$ begin create type confirmed_via as enum ('user', 'auto'); exception when duplicate_object then null; end $$;
do $$ begin create type capture_mode as enum ('default', 'one_click'); exception when duplicate_object then null; end $$;
do $$ begin create type provider as enum ('grok', 'gemini'); exception when duplicate_object then null; end $$;
do $$ begin create type job_status as enum ('queued', 'running', 'done', 'dead'); exception when duplicate_object then null; end $$;
do $$ begin create type ledger_reason as enum ('signup', 'referral_bonus', 'referred_signup', 'scan_used', 'refund', 'admin'); exception when duplicate_object then null; end $$;
do $$ begin create type referral_status as enum ('pending', 'released', 'blocked'); exception when duplicate_object then null; end $$;
do $$ begin create type subscription_store as enum ('apple', 'google'); exception when duplicate_object then null; end $$;
do $$ begin create type subscription_status as enum ('active', 'grace', 'expired'); exception when duplicate_object then null; end $$;
do $$ begin create type referral_code_kind as enum ('user', 'influencer'); exception when duplicate_object then null; end $$;
do $$ begin create type export_format as enum ('xlsx', 'pdf'); exception when duplicate_object then null; end $$;
do $$ begin create type export_job_status as enum ('queued', 'running', 'done', 'failed'); exception when duplicate_object then null; end $$;
do $$ begin create type push_platform as enum ('ios', 'android'); exception when duplicate_object then null; end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.health_check()
returns int
language sql
stable
as $$
  select 1;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  country text,
  default_currency text not null default 'USD' check (default_currency ~ '^[A-Z]{3}$'),
  referred_by_code text,
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id int generated by default as identity primary key,
  name text not null unique check (char_length(name) between 1 and 80),
  is_default boolean not null default true,
  is_system boolean not null default false
);

insert into public.categories (id, name, is_default, is_system) values
  (1, 'Travel & Transit', true, false),
  (2, 'Meals & Entertainment', true, false),
  (3, 'Office Supplies', true, false),
  (4, 'Software & IT', true, false),
  (5, 'Vehicle Expenses', true, false),
  (6, 'Advertising & Marketing', true, false),
  (7, 'Professional Services', true, false),
  (8, 'Utilities & Telecom', true, false),
  (9, 'Inventory & Materials', true, false),
  (10, 'Miscellaneous', true, true)
on conflict (id) do update set
  name = excluded.name,
  is_default = excluded.is_default,
  is_system = excluded.is_system;

select setval(pg_get_serial_sequence('public.categories', 'id'), 10, true);

create table if not exists public.user_categories (
  user_id uuid not null references public.profiles(id) on delete cascade,
  category_id int not null references public.categories(id),
  sort_order int not null default 0,
  primary key (user_id, category_id)
);

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  capture_id uuid not null unique,
  status receipt_status not null default 'processing',
  confirmed_via confirmed_via,
  capture_mode capture_mode not null,
  provider provider,
  merchant text,
  txn_date date,
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  total numeric(12,2),
  category_id int references public.categories(id),
  image_path text,
  notes text,
  search_text tsvector,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists receipts_user_txn_date_idx on public.receipts(user_id, txn_date desc) where deleted_at is null;
create index if not exists receipts_user_status_idx on public.receipts(user_id, status);
create index if not exists receipts_user_category_idx on public.receipts(user_id, category_id) where deleted_at is null;
create index if not exists receipts_search_text_idx on public.receipts using gin(search_text);

create table if not exists public.receipt_items (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null references public.receipts(id) on delete cascade,
  name text not null,
  qty numeric(8,2) not null default 1,
  amount numeric(12,2) not null default 0
);

create table if not exists public.extraction_jobs (
  id uuid primary key default gen_random_uuid(),
  receipt_id uuid not null unique references public.receipts(id) on delete cascade,
  status job_status not null default 'queued',
  attempt_count int not null default 0 check (attempt_count <= 3),
  next_retry_at timestamptz not null default now(),
  locked_at timestamptz,
  provider_attempted text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists extraction_jobs_status_next_retry_idx on public.extraction_jobs(status, next_retry_at);

create table if not exists public.provider_state (
  id smallint primary key default 1 check (id = 1),
  state text not null default 'closed' check (state in ('closed', 'open')),
  consecutive_failures int not null default 0,
  opened_at timestamptz,
  last_probe_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.provider_state (id) values (1) on conflict (id) do nothing;

create table if not exists public.scan_ledger (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  delta int not null,
  reason ledger_reason not null,
  ref_id uuid not null,
  created_at timestamptz not null default now(),
  unique (user_id, reason, ref_id)
);

create index if not exists scan_ledger_user_created_at_idx on public.scan_ledger(user_id, created_at);

create table if not exists public.referral_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-HJ-NP-Z2-9]{6}$'),
  kind referral_code_kind not null,
  owner_user_id uuid references public.profiles(id) on delete set null,
  commission_rate numeric(4,2),
  max_uses int,
  active boolean not null default true,
  payout_contact text
);

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  code_id uuid not null references public.referral_codes(id),
  referred_user_id uuid not null unique references public.profiles(id) on delete cascade,
  entry_method text not null check (entry_method in ('link', 'code')),
  status referral_status not null default 'pending',
  released_at timestamptz,
  fraud_flags jsonb not null default '{}'::jsonb
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  store subscription_store not null,
  product_id text not null check (product_id in ('rf_plus_699_m', 'rf_unlimited_1199_m')),
  status subscription_status not null,
  current_period_start timestamptz not null,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_events (
  id uuid primary key default gen_random_uuid(),
  rc_event_id text not null unique,
  user_id uuid references public.profiles(id) on delete set null,
  type text not null,
  gross_amount numeric(12,2),
  currency text,
  store text,
  occurred_at timestamptz,
  raw jsonb not null default '{}'::jsonb
);

create table if not exists public.commission_ledger (
  id uuid primary key default gen_random_uuid(),
  code_id uuid not null references public.referral_codes(id),
  payment_event_id uuid not null unique references public.payment_events(id),
  commission_amount numeric(12,2) not null,
  status text not null check (status in ('accrued', 'paid', 'reversed')),
  paid_at timestamptz
);

create table if not exists public.account_tombstones (
  user_id uuid primary key,
  deleted_at timestamptz not null default now(),
  purge_financial_at timestamptz not null
);

create table if not exists public.export_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  filters jsonb not null default '{}'::jsonb,
  format export_format not null,
  include_images boolean not null default false,
  status export_job_status not null default 'queued',
  file_path text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_tokens (
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text primary key,
  platform push_platform not null
);

create or replace function public.refresh_receipt_search_text(target_receipt_id uuid)
returns void
language plpgsql
as $$
begin
  update public.receipts r
  set search_text =
    setweight(to_tsvector('simple', coalesce(r.merchant, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(r.notes, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce((select string_agg(ri.name, ' ') from public.receipt_items ri where ri.receipt_id = r.id), '')), 'C')
  where r.id = target_receipt_id;
end;
$$;

create or replace function public.receipts_search_text_trigger()
returns trigger
language plpgsql
as $$
begin
  perform public.refresh_receipt_search_text(new.id);
  return new;
end;
$$;

create or replace function public.receipt_items_search_text_trigger()
returns trigger
language plpgsql
as $$
begin
  perform public.refresh_receipt_search_text(coalesce(new.receipt_id, old.receipt_id));
  return coalesce(new, old);
end;
$$;

drop trigger if exists receipts_set_updated_at on public.receipts;
create trigger receipts_set_updated_at before update on public.receipts for each row execute function public.set_updated_at();

drop trigger if exists receipts_refresh_search_text on public.receipts;
create trigger receipts_refresh_search_text after insert or update of merchant, notes on public.receipts for each row execute function public.receipts_search_text_trigger();

drop trigger if exists receipt_items_refresh_search_text on public.receipt_items;
create trigger receipt_items_refresh_search_text after insert or update or delete on public.receipt_items for each row execute function public.receipt_items_search_text_trigger();

drop trigger if exists extraction_jobs_set_updated_at on public.extraction_jobs;
create trigger extraction_jobs_set_updated_at before update on public.extraction_jobs for each row execute function public.set_updated_at();

drop trigger if exists export_jobs_set_updated_at on public.export_jobs;
create trigger export_jobs_set_updated_at before update on public.export_jobs for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, country, default_currency)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'country', null),
    coalesce(new.raw_user_meta_data->>'default_currency', 'USD')
  )
  on conflict (id) do nothing;

  insert into public.scan_ledger (user_id, delta, reason, ref_id)
  values (new.id, 10, 'signup', new.id)
  on conflict (user_id, reason, ref_id) do nothing;

  insert into public.user_categories (user_id, category_id, sort_order)
  select new.id, c.id, c.id
  from public.categories c
  where c.is_system = true
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.user_categories enable row level security;
alter table public.receipts enable row level security;
alter table public.receipt_items enable row level security;
alter table public.scan_ledger enable row level security;
alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;
alter table public.subscriptions enable row level security;
alter table public.export_jobs enable row level security;
alter table public.push_tokens enable row level security;

drop policy if exists "profiles owner select" on public.profiles;
create policy "profiles owner select" on public.profiles for select using (id = auth.uid());
drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "categories readable" on public.categories;
create policy "categories readable" on public.categories for select using (true);

drop policy if exists "user categories owner all" on public.user_categories;
create policy "user categories owner all" on public.user_categories for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "receipts owner all" on public.receipts;
create policy "receipts owner all" on public.receipts for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "receipt items owner all" on public.receipt_items;
create policy "receipt items owner all" on public.receipt_items for all using (
  exists (select 1 from public.receipts r where r.id = receipt_id and r.user_id = auth.uid())
) with check (
  exists (select 1 from public.receipts r where r.id = receipt_id and r.user_id = auth.uid())
);

drop policy if exists "scan ledger owner select" on public.scan_ledger;
create policy "scan ledger owner select" on public.scan_ledger for select using (user_id = auth.uid());

drop policy if exists "referral codes readable active" on public.referral_codes;
create policy "referral codes readable active" on public.referral_codes for select using (active = true or owner_user_id = auth.uid());

drop policy if exists "referrals owner select" on public.referrals;
create policy "referrals owner select" on public.referrals for select using (referred_user_id = auth.uid());

drop policy if exists "subscriptions owner select" on public.subscriptions;
create policy "subscriptions owner select" on public.subscriptions for select using (user_id = auth.uid());

drop policy if exists "export jobs owner all" on public.export_jobs;
create policy "export jobs owner all" on public.export_jobs for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "push tokens owner all" on public.push_tokens;
create policy "push tokens owner all" on public.push_tokens for all using (user_id = auth.uid()) with check (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false), ('exports', 'exports', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "receipt images owner read" on storage.objects;
create policy "receipt images owner read" on storage.objects for select using (
  bucket_id = 'receipts' and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "receipt images owner write" on storage.objects;
create policy "receipt images owner write" on storage.objects for insert with check (
  bucket_id = 'receipts' and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "exports owner read" on storage.objects;
create policy "exports owner read" on storage.objects for select using (
  bucket_id = 'exports' and auth.uid()::text = (storage.foldername(name))[1]
);
